CREATE TABLE "SNAPS" (
	"ID"		INTEGER NOT NULL,
	"TIMESTAMP"	INTEGER NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ITEMS" (
	"PATH"		TEXT NOT NULL,
	"HASH"		TEXT NOT NULL,
	"IS_DIR"	INTEGER NOT NULL,
	"UID"		INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("PATH", "HASH")
);

CREATE TABLE "LNK_ITEM_SNAP" (
	"UID"		INTEGER NOT NULL,
	"SNAP"		INTEGER NOT NULL,
	"MODE"		TEXT NOT NULL,
	"MOD_TIME"	INTEGER NOT NULL,
	PRIMARY KEY("UID", "SNAP"),
	FOREIGN KEY("UID") REFERENCES ITEMS("UID"),
	FOREIGN KEY("SNAP") REFERENCES SNAPS("ID")
);

CREATE TABLE "ROOTS" (
	"PATH"	TEXT NOT NULL,
	PRIMARY KEY("PATH")
);