CREATE TABLE "FS" (
	"PATH"	TEXT NOT NULL,
	"LEN"	INTEGER NOT NULL,
	"PERMS"	INTEGER NOT NULL,
	"FROM_GEN"	INTEGER NOT NULL,
	"TO_GEN"	INTEGER NOT NULL,
	"ID"	INTEGER NOT NULL,
	"STORED_IN"	INTEGER NOT NULL,
	"OFFSET" INTEGER NOT NULL,
	PRIMARY KEY("PATH","LEN","PERMS")
);

CREATE TABLE "SNAPS" (
	"ID"	INTEGER NOT NULL,
	"DATE"	INTEGER NOT NULL,
	PRIMARY KEY("GEN")
);

CREATE TABLE "PARAMS" (
	"KEY"	TEXT NOT NULL,
	"VAL"	TEXT,
	PRIMARY KEY("KEY")
);

CREATE TABLE "ROOTS" (
	"PATH"	TEXT NOT NULL,
	PRIMARY KEY("PATH")
);
