CREATE TABLE SNAPS (
	ID			INTEGER NOT NULL,
	TIMESTAMP	INTEGER NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE ITEMS (
	PATH		TEXT NOT NULL,
	SNAP		INTEGER NOT NULL,
	HASH		TEXT NOT NULL,
	IS_DIR		INTEGER NOT NULL,
	MODE		INTEGER NOT NULL,
	MOD_TIME	INTEGER NOT NULL,
	PRIMARY KEY(PATH, SNAP)
);

CREATE TABLE BLOBS (
	HASH			TEXT NOT NULL,
	SIZE			INTEGER NOT NULL,
	BLOB_SIZE		INTEGER NOT NULL,
	IS_COMPRESSED	INTEGER NOT NULL,
	IS_ENCRYPTED	INTEGER NOT NULL,
	PRIMARY KEY(HASH)
);

CREATE TABLE ROOTS (
	PATH	TEXT NOT NULL,
	PRIMARY KEY(PATH)
);